- name: Ensure apache2 installed
  apt:
    name: apache2
    state: latest

- name: Ensure apache2 started and enabled
  service:
    name: apache2
    state: started
    enabled: true

- name: ensure quiz-roles.conf.j2 is installed
  template:
    src: quiz-roles.conf.j2
    dest: /etc/apache2/sites-available/quiz-role.conf
    owner: root
    group: root
    mode: 0644

- name: Enable webserver configuration
  command: a2ensite quiz-role.conf

- name: Disable default webserver configuration
  command: a2dissite 000-default.conf
  notify:
  - restart apache2

- name: HTML Content is installed
  copy:
    src: html-quiz/
    dest: /var/www/quiz-roles/{{ ansible_hostname }}
    owner: root
    group: root
    mode: 0644
