- name: create user accounts for all servers
  hosts: managed
  become: true

  vars_files:
    - quiz-Secret.yml

  tasks:
    - name: create user form quiz-Secret.yml
      user:
        name: "{{username}}"
        password: "{{passwd | password_hash('sha512')}}"
